version: "3.9"

services:
  fbackend:
    build: ./backend
    container_name: fbackend
    restart: always
    env_file:
      - .env
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/flaskdb
    volumes:
      - ./backend:/app
    depends_on:
      - db
    expose:
      - "8000"

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flaskdb
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
    depends_on:
      - fbackend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
